rvm: 1.9.2
before_script:
  - psql -c 'create database picdrip_test;' -U postgres
  - bundle exec rake db:migrate
  - ./travis.sh
env:
  - WEB_DRIVER=firefox DISPLAY=:99.0
  - WEB_DRIVER=chrome DISPLAY=:99.0