:app:
  :tmp_dir: ./tmp
  :host: http://localhost:3000

:flickr:
  :api_key: aa88bc1aa2a62c87b745cab5d3ec7610
  :api_secret: c6769fefa9141dd4

:twitter:
 :consumer_key: hvlljOFXH9321xzIsYNOjQ
 :consumer_secret: gQ7bfs8xuDEArKTM12tsDw1dK3mG4sNYsjVy6HPVg
 :callback_url: http://drip.james.ottaway.mp/twitter/callback

:notifo:
 :username: flickrdripfeedtest
 :secret: c4ec07d20ad3a4d746b966d026cece7ca81f4e72