defaults: &defaults
  tmp_dir: ./tmp
  flickr_api_key: aa88bc1aa2a62c87b745cab5d3ec7610
  flickr_api_secret: c6769fefa9141dd4
  flickr_auth_token: 72157625985786952-06ac840235f42335

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
