postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5

default: &default
  <<: *postgresql
  username: postgres
  password: postgres

travis: &travis
  <<: *postgresql
  username: postgres
  password:

development:
  <<: *default
  database: picdrip_development

test:
<% if ENV['TRAVIS'] %>
  <<: *travis
<% else %>
  <<: *default
<% end %>
  database: picdrip_test

staging:
  <<: *default
  database: picdrip_staging

production:
  <<: *default
  database: picdrip
