development:
  adapter: postgresql
  encoding: unicode
  database: picdrip_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: picdrip_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: picdrip_production
  pool: 5
  username:
  password:
