postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5

default: &default
  <<: *postgresql
  username: postgres
  password: postgres

development:
  <<: *default
  database: picdrip_development

test:
  <<: *default
  database: picdrip_test

staging:
  <<: *default
  database: picdrip_staging

production:
  <<: *default
  database: picdrip
